admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 8000
dynamic_resources:
  cds_config:
    api_config_source:
      api_type: GRPC
      cluster_names:
      - xds_cluster
  lds_config:
    api_config_source:
      api_type: GRPC
      cluster_names:
      - xds_cluster
node:
  cluster: nick-xds
  id: test-id
static_resources:
  clusters:
  - connect_timeout: 1s
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 19000
    http2_protocol_options: {}
    name: xds_cluster
